### ISSUE TITLE
Add CI for building unit tests and coverage analysis

### ISSUE THREAD

**Issue by aentinger** [107-systems/107-Arduino-NMEA#2]
Hi @per1234 :wave: May I ask you to add CI to this repository for building and running unit tests as well as gathering coverage data? We might also consider transitioning to GitHub Actions since I'd really love to have the ressource consumption tracking available for our repositories. What do you think?

**Comment by per1234** [comment]
Sure! Should I submit the PR against the `master` or `nmea-parser` branch?

I did a test run on `nmea-parser` and it failed, but I think it's a legitimate failure, rather than a problem with the CI config:
https://github.com/per1234/107-Arduino-NMEA/runs/839062656?check_suite_focus=true

**Comment by aentinger** [comment]
Good Morning :wave: I'd prefer to have the PR against `nmea-parser` since that's the one I'll be working for quite some time still before it will be merged into master. I've looked at your actions log but didn't really understand what happened there - regardless let's create the PR against this branch and then let's fix any remaining issues.

**Comment by aentinger** [comment]
Fixed by #3.
